function adaptive_help() {
	if [ "$1" == "hosts" ]; then
		echo "==> hosts"
		echo "Description: Simply lists all the available"
		echo "  hosts in your ssh config"
		echo "Parameters:"
		echo "  - hosts <string> - Does a regex search for"
		echo "      hosts that contain that string, e.g.  "
		echo "      'hosts mencap'"
	elif [ "$1" == "exp" ]; then
		echo "==> exp"
		echo "Description: Will iterate through you ~/.aws/"
		echo "  credentials file and list the exp servers"
		echo "Parameters:"
		echo "  No parameters for this command"
	elif [ "$1" == "local_copy" ]; then
		echo "==> local_copy"
		echo "Description: List all the sites from apache"
		echo "  and their directory, also allowing you to"
		echo "  make a copy of that site locally"
		echo "Parameters:"
		echo "  - local_copy <host> - View all sites on"
		echo "      the host provided, you can use 'hosts'"
		echo "      to get a list of available hosts"
	elif [ "$1" == "dx" ]; then
		echo "==> dx"
		echo "Description: Simplest command goes to the"
		echo "  directory ~/docker/<directory> and runs"
		echo "  the command for the php docker container"
		echo "Parameters:"
		echo "  - dx <directory>"
	elif [ "$1" == "site_search" ]; then
		echo "==> site_search"
		echo "Description: Simply searchs our internal"
		echo "  server for a certain domain to help you"
		echo "  find what server it is on"
		echo "Parameters:"
		echo "  - site_search <part_of_domain>"
	else
		echo "=========================================="
		echo "         Adaptive Linux Tools             "
		echo "=========================================="
		echo " A set of tools and commands created and  "
		echo " maintained by Adaptive                   "
		echo "   COMMANDS:"
		echo "     - hosts"
		echo "     - exp"
		echo "     - local_copy"
		echo "     - dx"
		echo "     - site_search"
		echo ""
		echo " Type 'adaptive_help <command>' for more"
		echo " info and usage of that command"
		echo "=========================================="
	fi
}